site_name: æ°å®çš„Wiki
site_description: æ°å®çš„Wiki
copyright: Copyright Â© 2022
site_url: https://wiki.beiklive.top/
repo_url: https://github.com/Ohto-Ai/blog
site_description: Blog for beiklive
site_author: beiklive

nav:
  - ğŸ¤¯ä¸»é¡µ: index.md
  - ğŸ’©ä»£ç ç¬”è®°: 
    - ğŸ¤ªPython:
      - Pythonç¬”è®°: docs/Python/python.md
    - ğŸ§C++:
      - C++ç¬”è®°: docs/C++/c++.md
      - QTç¬”è®°: docs/C++/QT.md
      - è®¾è®¡æ¨¡å¼: docs/C++/design-patterns.md
      - 30å¤©ç¼–å†™C++æœåŠ¡å™¨: docs/C++/30daymakecppserver.md
      - çº¿ç¨‹æ± : docs/C++/ThreadPool.md
    - ğŸ˜´Nodejs:
      - Nodejsç¬”è®°: docs/Nodejs/nodejs.md
      - pm2ä½¿ç”¨: docs/Nodejs/pm2.md
  - ğŸ¤ Linuxç›¸å…³:
    - ğŸ‘“ubuntu: docs/Linux/ubuntu.md
    - ğŸ“–I/Oå¤šè·¯å¤ç”¨: docs/Linux/IOå¤šè·¯å¤ç”¨.md
    - ğŸˆ²æ ‘è“æ´¾: docs/Linux/æ ‘è“æ´¾.md
  - ğŸ“–å¤é›†å…«å­¦:
    - ğŸš®nginx: docs/other/nginx.md
    - â˜¢ï¸æ­£åˆ™è¡¨è¾¾å¼: docs/other/regx.md
    - ğŸ’£wslç®¡ç†å™¨: docs/other/wsl.md
    - âš“ä¸­å›½ç¨‹åºå‘˜å®¹æ˜“å‘éŸ³é”™è¯¯çš„å•è¯: docs/other/duyin.md
  - ğŸ‰‘å…³äº: about.md

theme:
  name: material
  logo: img/favicon.svg
  favicon: img/favicon.svg
  language: zh
  font:
    text: Roboto
    code: Roboto Mono

  include_search_page: false
  search_index_only: true
  palette: 
    - media: "(prefers-color-scheme: light)"
      primary: white
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes 
    - toc.follow
    # - toc.integrate 
    - navigation.top
    # - announce.dismiss
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - announce.dismiss
    - content.code.annotate 
social:
  - icon: 'fontawesome/brands/github'
    link: 'https://github.com/beiklive'
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html
extra_css:
  - stylesheets/extra.css
